### ISSUE TITLE
Multiple panels in a row get stacked in one row

### ISSUE THREAD

**Issue by coleenquadros** [grafana/jsonnet-libs#1000]
Hi, as a part of an overview dashboard the intention is to create multiple rows with 8 or more panels. I created a row that had 8 panels and provided the grid pos in such a way that 4 panels are on the first line and next 4 on the second line. However when I copy the JSON on to grafana, the dashboard is rendered such that all 8 panels get stacked in one line. Am I missing something?

These are the grid pos I provided for the panels
first line in the row
```
gridPos: { x: 0, y: 1, w: 6, h: 6 }
gridPos: { x: 6, y: 1, w: 6, h: 6 }
gridPos: { x: 12, y: 1, w: 6, h: 6 }
gridPos: { x: 18, y: 1, w: 6, h: 6 }
```

second line in the [row](url)
```
gridPos: { x: 0, y: 7, w: 6, h: 6 }
gridPos: { x: 6, y: 7, w: 6, h: 6 }
gridPos: { x: 12, y: 7, w: 6, h: 6 }

```
![Screenshot 2023-06-28 at 16 50 46](https://github.com/grafana/jsonnet-libs/assets/22583887/5027da03-67b1-41e0-9909-91eb6d017902)

**Comment by v-zhuravlev** [comment]
Hello, I think this question is not related to any of jsonnet libs present in this lib, but about building Grafana dashboards in jsonnet. 
Please take a look at grafonnet and its grid util functions:
https://grafana.github.io/grafonnet/API/util.html#obj-grid
