### ISSUE TITLE
Windows fleet overview links don't keep datasource

### ISSUE THREAD

**Issue by clementduveau** [grafana/jsonnet-libs#1221]
In windows-observ-lib, line 81, the URL doesn't keep the datasource (which is a variable in the dashboard).

We need to use something like `d/%s?var-%s=${__data.fields.%s}&${__url_time_range}&${datasource:queryparam} % [this.grafana.dashboards.overview.uid, instanceLabel, instanceLabel]`

Will do it later when I have time.

**Comment by v-zhuravlev** [comment]
Fixed in #1222
