### ISSUE TITLE
Update README's to reference tanka

### ISSUE THREAD

**Issue by abh** [grafana/jsonnet-libs#185]
It'd be nice if the various README's referenced and gave instructions for tanka instead of ks (since that's now a dead project, right?).

**Comment by abh** [comment]
For example in https://github.com/grafana/jsonnet-libs/tree/master/prometheus-ksonnet

**Comment by malcolmholmes** [comment]
This has actually been done. The linked page refers to Tanka now.

**Comment by malcolmholmes** [comment]
Actually, `grep` shows me I'm overstating that. It has been solved in *that* location. Let me look at a few more now,

**Comment by malcolmholmes** [comment]
See https://github.com/grafana/jsonnet-libs/pull/289

**Comment by Duologic** [comment]
This was resolved by https://github.com/grafana/jsonnet-libs/pull/289
