### ISSUE TITLE
Direct PersistentVolumeClaim instantiation not possible due to an overwritten new() in kausal.libsonnet

### ISSUE THREAD

**Issue by jheyduk** [grafana/jsonnet-libs#197]
I'm using tanka and wanted to create PVCs for using them as a shared filesystem for different Deployments.
This is not possible because of an overwritten new()-method which drops the apiVersion/kind properties during creation.
For StatefulSets there should be another type which should be used `PersistentVolumeClaimTemplates`. See #77 for details.

**Comment by jheyduk** [comment]
The mentioned type is already existing. It is `persistentVolumeClaimSpec`

**Comment by Duologic** [comment]
I've refactored most of ksonnet-util recently. Is this still a problem?
