### ISSUE TITLE
Deployment creation should not add labels

### ISSUE THREAD

**Issue by prune998** [grafana/jsonnet-libs#207]
Why is the `deployment` adding a `name` label by default ? 

https://github.com/grafana/jsonnet-libs/blob/054e9373afea835198d14a109a62f14f41441ae7/ksonnet-util/kausal.libsonnet#L146

From my point of view it could be `app` like most deployments use, but the best would be to add nothing. Maybe just add if labels are empty ? ( but I still prefer `app` over `name`).

I could submit a PR ? 
Any comment welcome.

Thanks

**Comment by Duologic** [comment]
This is an opinionated label and common for grafana, we use it quite widespread. If you need overriding, the lease annoying way it is to hide it in jsonnet.

```jsonnet
deployment.new(name, containers, podLabels={name:: null})
```

I hope this answers your question.
