### ISSUE TITLE
Rename and tweak prometheus-ksonnet

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/jsonnet-libs#216]
Given ksonnet is deprecated, calling this lib `prometheus-ksonnet` doesn't make sense. Therefore, I propose we rename it `prometheus-mixin`. We can leave behind a `prometheus-ksonnet` that will allow for previous installations to still work.

I also propose:
* Move the Grafana related code into a separate `grafana-mixin`, and have `prometheus-mixin` import it via `jb`.
* Switch Grafana to a statefulset and give it a small PVC for its sqlite db. This will preserve alert IDs, and also preserve dashboards that users create manually, before they learn the wonders of dashboards as code.
* Update Grafana to the latest version
* Reduce the size of the Prometheus PVC. 300Gb is pretty big for an initial install. We should optimise for new user experience. Experienced users can adjust the PVC size to suit.
* Explore making `$.grafana_add_datasource...` less Prometheus focused. Allow it to be used for non Prometheus datasources, without making prometheus related code more verbose.

**Comment by malcolmholmes** [comment]
Also, if we are allowed to use Grafana _without_ prometheus, then we will need to extract the nginx instance out of `prometheus-ksonnet` and make it into a separate 'dashboard' (but with another name though!).

It would also be good to apply some basic styling to the nginx index page.

**Comment by trotttrotttrott** [comment]
I agree we should plan to rename. But there already is a `prometheus-mixin` - https://github.com/prometheus/prometheus/tree/master/documentation/prometheus-mixin. I think we're still trying to formalize what a "mixin" is, but most that use that suffix so far only contain alerting rules, recording rules, and/or dashboards. Whereas this is to supplement the creation of k8s manifests. In which case perhaps `prometheus-lib` would be a more appropriate name? Also, `grafana-lib` instead of `grafana-mixin`?

**Comment by malcolmholmes** [comment]
I've been having this conversation with @sh0rez. Strictly, a 'mixin' is just a thing that you use to alter and modify another thing. However, it seems that the term 'monitoring mixin' has leached, and taken over the simpler 'mixin' term in the Jsonnet world, so when people hear 'mixin' they think of a monitoring one.

In that scenario, yes, it should be named differently.

@sh0rez has also been thinking about how libraries are structured generally. We may end up with a very different (cleaner) set of libraries (but with a migration path) soon. Watch this space.

**Comment by tomwilkie** [comment]
+1 `prometheus-lib` and `grafana-lib`, although have you considered just `prometheus` and `grafana`?  

> Move the Grafana related code into a separate grafana-mixin, and have prometheus-mixin import it via jb

+1 I did most of that here already: https://github.com/grafana/jsonnet-libs/pull/232

> Switch Grafana to a statefulset and give it a small PVC for its sqlite db. This will preserve alert IDs, and also preserve dashboards that users create manually, before they learn the wonders of dashboards as code.

Not sure how I feel about this: the whole point of this library is to build stateless Grafanas.  If we want a stateful Grafana, we should use & dogfood the hosted Grafana.

> Reduce the size of the Prometheus PVC. 300Gb is pretty big for an initial install. We should optimise for new user experience. Experienced users can adjust the PVC size to suit.

In general, scaling has always been a problem with this library.  The same goes for memory and CPU requests.  Not sure what to do about it, but right now we are not optimising for new users, we are optimising for production.  I think it fine to have a set of overrides for play time, but I want this library to be production-focused.

**Comment by tomwilkie** [comment]
> Update Grafana to the latest version

And kube-state-metrics, and push-exporter, and alert manager etc.

It would be good to find a way to automate this.

> Explore making $.grafana_add_datasource... less Prometheus focused. Allow it to be used for non Prometheus datasources, without making prometheus related code more verbose

+1

**Comment by tomwilkie** [comment]
There is also a long list of things to tidy up: https://github.com/grafana/jsonnet-libs/issues/160

**Comment by woodsaj** [comment]
is it possible to extend the "mixin" model to additionally include "scrape_configs".  It is not common, but there are instances where developers will want to add custom scrape_configs.

**Comment by tomwilkie** [comment]
It is possible, but right now mixins don't specify how things are deployed - ie they don't specify kubernetes service discovery, or dns etc.  Therefore it would be a little weird.  The way we wrap mixins internally should allow us to be more opinionated, as should the cloud agent.

**Comment by malcolmholmes** [comment]
> is it possible to extend the "mixin" model to additionally include "scrape_configs". It is not common, but there are instances where developers will want to add custom scrape_configs.

I'm thinking about another thing that sits alongside a mixin. I've used the term "opinionated mixin", although I'm sure there are better ones. A Mixin is deliberately specified as environment agnostic. But libraries that install mixins need to know about environment specifics. E.g. prometheus-ksonnet can consume `grafanaDashboards`. It would be good to document a standard way to define these things. This could also include `scrape_configs` as they would be similarly environment specific. We just need to name the concept. One of the RedHat guys suggested the name Bundle for a similar problem.

**Comment by malcolmholmes** [comment]
This ticket has been superseded. Prometheus, Alert Manager, Nginx, Grafana have all been extracted out of Prometheus-Ksonnet into their own self-contained libraries, whilst (attempting to) maintain backwards compatibility. Thus, prometheus-ksonnet still exists, but is a much smaller thing than it once was. Maybe, at some point, once enough functionality has been moved else where, we might choose to deprecate prometheus-ksonnet, but likely not for a while.
