### ISSUE TITLE
Support dashboards auto gen in CI

### ISSUE THREAD

**Issue by yeya24** [grafana/jsonnet-libs#229]
There are many dashboards mixins in this repo. However, it just provides a `dashboards.jsonnet` file, but not everyone has jsonnet experience. Maybe it is better to add a dashboards auto gen in circle CI so that users can use the dashboard file directly.

**Comment by paulfantom** [comment]
I created a site which solves this problem, available at http://monitoring.mixins.dev/ :)

**Comment by jdbaldry** [comment]
@paulfantom This is really great, thanks for doing it!
I'm looking to introduce a new library shortly that I plan to do versioned releases for. Would you have any thoughts on how releases could be incorporated into your monitoring mixins site?

**Comment by paulfantom** [comment]
Currently, the site only generates content from the latest commit of the default branch of various mixins. There are two things we would need to consider when adding releases:
- content generation
- content presentation

From the generation side of things, we can just download all releases and generate mixins in subdirectories. From the presentation side, we probably will need to adjust or change the current site theme to support this (truth to be told I don't like few things in the current theme, so it might be good to fix those at the same time). Maybe something like a dropdown for each mixin in the left navigation panel would be good?

I am open to suggestions on how to add this functionality but let's move this discussion to https://github.com/monitoring-mixins/website :)
