### ISSUE TITLE
etcd-operator doesn't create CRD

### ISSUE THREAD

**Issue by amckinley** [grafana/jsonnet-libs#276]
The resulting manifests from the `etcd-operator` jsonnet library are missing the definition of `EtcdCluster`, causing any libraries that depend on them to fail to `tk diff` or `tk apply` if the target cluster isn't already configured with that CRD.

**Comment by tomwilkie** [comment]
I believe the operator creates the CRD when it runs - so it might be that the first apply fails, but the second one succeeds?

**Comment by Duologic** [comment]
It looks like this has been answered without a follow up response, closing.
