### ISSUE TITLE
Confusion regarding ksonnet and k8s-alpha

### ISSUE THREAD

**Issue by rrichardson** [grafana/jsonnet-libs#288]
It appears that the new (old?) ksonnet at https://github.com/kube-jsonnet/k is officially deprecated in favor of k8s-alpha.

However, it appears that all *sonnet deployments under the Grafana umbrella are still using the above ksonnet libs. 
Also, the k8s-alpha README states that it is still experimental.  

I am embarking on beginning to unify and port deployments for a few k8s clusters to a single, unified config management system and I'd really like to use Tanka.  I'm still learning jsonnet, so I'm still not completely clear on how to design the repository. 

Should I: 
* Still only use kube-jsonnet/k for now?
* Install both k8s-alpha and kube-jsonnet/k and use the existing grafana, loki, prometheus jsonnet-libs as-is? 
* Port everything to k8s alpha?

Are there experimental */jsonnet-libs branches which use k8s-alpha?   What is the intended roadmap for migrating towards it?

**Comment by rrichardson** [comment]
While I'm at it.  Do Grafonnet and Grafana-builder achieve the same result?  Is there a preferred approach? Also, how does Grizzly play into this?

**Comment by malcolmholmes** [comment]
@rrichardson lots of questions!

Firstly k8s-alpha. We have just created this new library (well, @sh0rez did). Before we can say to the world "use it" we want to run it ourselves for a while, and we're doing that. So far, without noticeable issue. But it will still take a while before we are ready to promote transitioning to it more widely. What does that mean for you? I'd say there's a mild risk around using something so new (but there's major risk using something outdated and deprecated!). With that in mind, make your own decision. Oh, and did I say that k8s-alpha has decent docs? :-)

Regarding other Grafana libraries. Do these other libraries *explicitly* depend upon kube-jsonnet? We are running them here at Grafana, using the new k8s-alpha library. If there are hard references, then we will over time need to migrate them, but I'm not aware of any. We removed the old library from out codebase, and things still work.

Regarding grafonnet/grafana-builder. These were created independently at a similar time. The authors were unaware of each other at the time. They have different nuances. At some point I'd like to see us integrate these (grafonnet covers everything, grafana-builder aims to keep dashboard building down to just providing another query string). Hopefully we will get to it. Again, use whichever suits your need the best. Note though that, at the moment, they are both community maintained. I suspect that Grafonnet is getting a little more attention though, even if using it is likely to be more verbose.

Regarding Grizzly. This is a (very new) tool aimed at deploying resources within Mixins directly to Grafana (at present it handles dashboards. I'm looking at adding datasources, notification channels, etc). To my mind it covers two use-cases: developer and non-k8s.

As a developer of a monitoring mixin, pushing my code to Grafana via k8s for each and every tweak is impractical, it takes too long. Grizzy allows for far faster iteration there (e.g. new 'preview' function that pushes to dashboard snapshots). Eventually though, the code will be deployed to Grafana via k8s using something like Tanka.

The other use-case is non-k8s. Grizzly will allow people not using Kubernetes to still use and deploy mixins to their infrastructure, (hopefully) vastly widening their appeal.

But please remember that Grizzly is still very new. Ideas, patches, etc are very welcome.

Does that answer your questions?

**Comment by rrichardson** [comment]
@malcolmholmes - Thanks for clearing that up.  That was very helpful.   

I'm still not quite clear on the k8s-alpha vs kube-jsonnet/k transition.   They are similar API, but certainly not a 1-to-1 mapping.  
k8s-alpha doesn't have the `mixin` in its paths, from what I can tell.  In k8s-alpha, the mixins are specially named functions in each k8s Type, (which is a better design, IMO)    The end result, though is that the kausal-util lib that is directly referenced by a `prometheus-ksonnet` and others,  can only work with kube-jsonnet/k.  That is unless there is a release of these libs that I'm not aware of.   I reckon the kausal-util lib would be the perfect place to abstract over the differences  of the two libs.  However, there are plenty of places where the k api is referenced explicitly,  e.g.  https://github.com/grafana/jsonnet-libs/blob/master/prometheus-ksonnet/lib/alertmanager.libsonnet#L157-L158

Do you use prometheus-ksonnet internally?  

I've found that even when using kube-jsonnet/k  I can get pretty much everything to work except Grafana.  After startup, it fails to find  `/graphana/dashboards`.  I have been experimenting all morning trying to get it to work.   I am not sure if the kubernetes-mixin is the issue or what, but the grafana/deployment.jsonnet creates and mounts the directories `/grafana/dashboard_kubernetes_[1-8]`  but it doesn't appear that anything creates /grafana/dashboard.  Looking at my previous system which was installed from a helm chart, the directory is `/var/lib/grafana`  I've tried to create that with a mount, but I am still missing some things.  I've started digging through the source to see what knobs I need to turn. 

P.S. 
In looking for the code link in github,  I noticed that what is installed by `jb` is not what's in master.  I assumed it just pulled the code out of git.  I will see about installing from master to see if that changes anything.  The grafana jsonnet lib under prometheus-ksonnet hasn't changed in 3 months, so I'm not sure that it well.

**Comment by sh0rez** [comment]
Hey @rrichardson!

Quick background on those 3 projects:

- ksonnet-lib: Created as part of ksonnet, a Heptio project. Deprecated around 2018/2019
- kube-jsonnet/k: hard fork of ksonnet-lib, done during FOSDEM 2020, by @metalmatze and me. Quickly abandoned as we realized the code is harder to maintain than to rewrite
- jsonnet-libs/k8s: the rewrite. Not 100% compatible, but similar. Does some different design choices, which we think are good.

Regarding the mixin subkey, it is available in all 3 implementations. The rewrite however does not need it, but support it as an alias.

The kausal lib is compatible to the rewrite as well, as long as you use kausal-shim, check the jsonnet-lib/k8s readme for that.

We also work on refactoring and uniting kausal and the rewrite, so there will only be a single thing left, but we are not there yet.

For the direct references of ksonnet-lib code, this is an issue and needs to be fixed. Please open issues when you find this and tag me or @malcolmholmes. 

Yes, we do use prometheus-ksonnet with the rewrite and experience no problems afaict.

**Comment by rrichardson** [comment]
I think I've managed to get a configuration that deploys.  My last issues were that nothing creates the `/var/lib/grafana` and `graphana/dashboards` directories.  I solves the problem my creating PVCs and mounting them to those directories.  

The last issue is one for which I can't find the solution (or the precise cause)  I am hoping for some guidance here: 

All of the stock dashboards for kubernetes-mixin that were deployed by default in prometheus-ksonnet installed correctly and work quite well.

What fails is adding a new data source, or trying to create a new dashboard.  When I attempt this, I get a `Data Proxy Error`.   I don't fully understand the architecture, but it appears that when the browser needs data, it can access it through the proxy correctly.  However, when Grafana itself needs to access the data sources (or proxy?) it fails.  I have included the logs below. 

I am really hoping I did something boneheaded in the configuration, but the only relevant config I have found is
 `root_url`  which I have set to my outer Ingress hostname FQDN.  i.e. `https://grafana.test.mydomain.com` 

```
t=2020-07-18T00:40:53+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/2/api/v1/query_range remote_addr=100.96.10.78 referer="https://grafana.test.mydomain.letter.co/dashboard/new?editPanel=2&orgId=1" error="http: proxy error: context canceled"
t=2020-07-18T00:40:53+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/2/api/v1/query_range status=502 remote_addr=100.96.10.78 time_ms=862 size=0 referer="https://grafana.test.mydomain.letter.co/dashboard/new?editPanel=2&orgId=1"
t=2020-07-18T00:41:12+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/2/api/v1/query_range remote_addr=100.96.10.78 referer="https://grafana.test.mydomain.letter.co/d/Q4pM2bnGz/testing?orgId=1" error="http: proxy error: EOF"
t=2020-07-18T00:41:12+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/2/api/v1/query_range status=502 remote_addr=100.96.10.78 time_ms=5377 size=0 referer="https://grafana.test.mydomain.letter.co/d/Q4pM2bnGz/testing?orgId=1"
t=2020-07-18T00:41:12+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/2/api/v1/query_range remote_addr=100.96.10.78 referer="https://grafana.test.mydomain.letter.co/dashboard/new?editPanel=2&orgId=1" error="http: proxy error: dial tcp 100.66.81.154:80: connect: connection refused"
t=2020-07-18T00:41:12+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/2/api/v1/query_range status=502 remote_addr=100.96.10.78 time_ms=19850 size=0 referer="https://grafana.test.mydomain.letter.co/dashboard/new?editPanel=2&orgId=1"
```

**Comment by malcolmholmes** [comment]
can you post how you invoked prometheus-ksonnet somewhere? While it isn't always as clear as it could be, I've always found prometheus-ksonnet just works, so I suspect you're doing something unexpected.

**Comment by rrichardson** [comment]
@malcolmholmes   

 main.jsonnet   https://gist.github.com/rrichardson/13097b8df97048a54f5594f3ef26157a

**Comment by malcolmholmes** [comment]
Nothing immediate stands out. You don't include k in your root object (just kops and prometheus) but I assume you have added that in a main.jsonnet, otherwise it would totally fail.

Not also that this setup is designed to be stateless so you don't need the PVCs. The only thing that will need state is using Grafana alerts, or manually created dashboards, but you have Jsonnet for dashboards and Alertmanager for alerts, so stateless should be fine.

I can take a deeper look later.

**Comment by malcolmholmes** [comment]
I will also note that we don't use kops. It is possible that code has become out of date.
