### ISSUE TITLE
Change Grafana link to land on search page.

### ISSUE THREAD

**Issue by slim-bean** [grafana/jsonnet-libs#300]
Currently the link to Grafana lands on the home page for Grafana:

https://github.com/grafana/jsonnet-libs/blob/f20b163eb12c1a4070c03cd30f292fbf900acf33/prometheus-ksonnet/lib/config.libsonnet#L14

99% of the time I will have to click on the dashboards dropdown or the search magnifier to get to the list of dashboards/folders to navigate to the dashboard I want.

I'm suggesting we add `?search=open` to the Grafana URL to automatically bring up the list of dashboards.

My only concern here is people outside of Grafana with different workflows being handed this change and breaking their workflow.

One alternative to this would be a variable you could set in the config to append this query parameter which is not set by default.

Thoughts/opinions anyone?

**Comment by robx** [comment]
Feels like ideally this'd be fixed in Grafana itself. I certainly run into the same thing whenever I open any Grafana; the intuitive thing I then do is try clicking the "Home" dashboard title, at which point I start grumbling UX !@$%!%. 😅
