### ISSUE TITLE
prometheus-ksonnet: Create Separate ConfigMaps for Configuration and Rules

### ISSUE THREAD

**Issue by trotttrotttrott** [grafana/jsonnet-libs#306]
We're currently putting `alerts.rules`, `prometheus.yml`, and `recording.rules` into a single ConfigMap. We've gotten to the point where the combined size of those files have become too long. We're getting the error:

> Name: "prometheus-...-config", Namespace: "default"
> for: "STDIN": ConfigMap "prometheus-...-config" is invalid: metadata.annotations: Too long: must have at most 262144 characters

I understand this is due to exceeding the max annotation size while attempting to set the `kubectl.kubernetes.io/last-applied-configuration` annotation. Violating the annotation size constraint makes the apply fail.

As a solution, I'd like to propose we break up this single ConfigMap into three, one for each file.

**Comment by trotttrotttrott** [comment]
Related issue: https://github.com/kubernetes/kubectl/issues/712

**Comment by malcolmholmes** [comment]
Temporary solution is to export the yaml configs, and use `kubectl replace -f` rather than `kubectl apply -f`. This doesn't write the annotation, and therefore works, but is an ugly hack.

**Comment by malcolmholmes** [comment]
Simplest solution:

Split configs into one for each of `prometheus.yml`, `alerts.rules` and `recording.rules`. However, this just delays the issue. It will come back when either of the `.rules` files have doubled in size.

Therefore, I think we should follow the model already taken with dashboards.

We now have a single configmap (or set of configmaps) per mixin. My suggestion is that we refactor this library to create a single configmap for `prometheus.yml`, then have one more configmap *per mixin*. These configmaps will contain an `alerts.rules` and `recording.rules` files just for this mixin.

This means that a single mixin would have to exceed the 280k (ish) limit on its own - much harder than now.

Also, it makes the resultant configuration easier to read, as the source of any rule is easier to identify (by filename).

**Comment by jdbaldry** [comment]
I think that a per mixin configmap isn't a bad idea, though I wonder about a configmap mount limit that we may also run into? I think we can avoid that by splitting the rules arrays into multiple files that can be then spread across configmaps like we do with grafanaDashboards maybe?

**Comment by beorn7** [comment]
I like the configmap-per-mixin idea, but I don't know anything about configmap mount limits and if that will get us in trouble with them.

**Comment by jdbaldry** [comment]
I want to expand on my previous comment a little as I used some ambiguous language in the context of Kubernetes.

I like the per configmap mixin idea. I don't imagine it would be likely that users would encounter any configmap object quota limit (I expect our target users would be able to increase this anyway) but I wonder if there are total container volume mount, or total pod configmap volume restrictions that we may encounter? I didn't find anything with a cursory search but did confirm with testing that you can at least create a pod with a hundred emptyDir mounts.

One slight complication I foresee with the configmap per mixin approach is that we will need to ensure separate mount paths for each mixin and appropriately configure the prometheus.yml rule_files globs but that shouldn't be too complicated.

**Comment by malcolmholmes** [comment]
> One slight complication I foresee with the configmap per mixin approach is that we will need to ensure separate mount paths for each mixin and appropriately configure the prometheus.yml rule_files globs but that shouldn't be too complicated.

But that's what Jsonnet is good at :-)
