### ISSUE TITLE
upstream memcached mixin

### ISSUE THREAD

**Issue by roidelapluie** [grafana/jsonnet-libs#389]
What would you think about ustreaming this mixin in the memcached_exporter repository? thanks!

**Comment by Duologic** [comment]
That doesn't sound like a bad idea. @tomwilkie @pracucci @malcolmholmes are the top 3 editors of that mixin, maybe they have stronger opinions?

**Comment by tomwilkie** [comment]
Love it!

**Comment by tomwilkie** [comment]
@sdboyer can you work with @roidelapluie to move this please?

**Comment by pracucci** [comment]
@sdboyer Has this been done or is it still an open issue?

**Comment by sdboyer** [comment]
Oh, whoops! Fell off my radar. Yeah, this is still an issue, i'll assign it to myself and see if i can find time next week.

**Comment by sdboyer** [comment]
Gonna pass this one to @rgeyer, seeing as how it's slipped for me again!

**Comment by rgeyer** [comment]
Okay, now I'm being delinquent on this 😞.

@roidelapluie Does anything in-particular need to happen here, or is this just a matter of submitting a PR to [the memcached repo](https://github.com/memcached/memcached)?

Happy to get this drafted today even, lest there are other steps I'm missing or overlooking?
