### ISSUE TITLE
missing name argument for [cluster]role / [cluster]rolebinding in ksonnet-util 

### ISSUE THREAD

**Issue by mbarbero** [grafana/jsonnet-libs#438]
The following constructors are called from `ksonnet-util/utils.libsonnet#namespacedRBAC` and `ksonnet-util/utils.libsonnet#rbac`:

- clusterRole.new()
- clusterRoleBinding.new()
- role.new()
- roleBinding.new()

and they all miss the mandatory `name` argument leading to the following error:

```
RUNTIME ERROR: Missing argument: name
        vendor/jsonnet-libs/ksonnet-util/util.libsonnet:88:7-24       object <anonymous>
```

**Comment by mbarbero** [comment]
I'm just starting using this lib and noticed that the `ksonnet-util` is under refactoring. Please disregard this issue if `utils.libsonnet` is not (yet) meant to be used standalone from `k8s-alpha`.

**Comment by asymmetric** [comment]
I stumbled upon a similar issue, where I couldn't use the `util.rbac` function from `ksonnet-util/kausal.libsonnet`: it would always complain a namespace was missing, even when I explicitly defined one in a `_config` object which I merged with the rest.

I ended up importing `util` from `ksonnet-util/util.libsonnet` directly (which doesn't have [these overrides](https://github.com/grafana/jsonnet-libs/blob/d4ab1666b96ba2830b2cde6526f54fac11f959b0/ksonnet-util/kausal.libsonnet#L16-L19)), and that worked perfectly.
