### ISSUE TITLE
enterprise-metrics: gossip-ring service does not include store-gateway, admin-api, or compactor

### ISSUE THREAD

**Issue by jtlisi** [grafana/jsonnet-libs#524]
The upstream gossip library for cortex-jsonnet library only includes the `ingesters`, `distributors` and `queriers` in the gossip ring service and in the instrumented gossip alerts. These must be expanded to include the `admin-api`, `compactor` and `store-gateway`.

<img width="1680" alt="Screen Shot 2021-03-23 at 3 03 41 PM" src="https://user-images.githubusercontent.com/6921077/112203491-f7bd8b80-8be8-11eb-88d5-0e96dd20e855.png">

**Comment by jdbaldry** [comment]
closed by #523
