### ISSUE TITLE
Update node-exporter

### ISSUE THREAD

**Issue by beorn7** [grafana/jsonnet-libs#527]
Node-exporter is still at v0.18.1 in here. Upstream has arrived at v1.1.2.

The update has to be performed with caution. Command line flags and metrics have changed. Rules (including alerts) and dashboards have to be checked for required changes (but what comes from the current version of the node-mixin should actually work just fine with the current version and might have problems with v0.18.1, but perhaps we vendor an older version of the node-mixin internally?).

I think this would be a great starter project for a new member of the cloud-platform team. It's relatively straight-forward but touches quite a few parts of the monitoring stack. /cc @macgreagoir in case you have someone up your sleeves.

**Comment by beorn7** [comment]
Assigning to myself just to keep track (and do it myself of nobody else gets to it).

**Comment by beorn7** [comment]
Anh now I see @simonswine has already started to work on this a week ago. Assigning to him, and sorry for the confusion.

**Comment by simonswine** [comment]
This is almost done now. Some drone nodes still seem to run an ancient version of node exporter (v0.9.1)

![scrn-2021-05-14-10-49-31](https://user-images.githubusercontent.com/223048/118253880-5d6c1c80-b4a2-11eb-84b6-564e6f20deae.png)

**Comment by simonswine** [comment]
Turns out v0.9.1 refers to the Grafana Agent. So this should be complete
