### ISSUE TITLE
Enhancement: strip -metrics ports out of Service definition

### ISSUE THREAD

**Issue by bboreham** [grafana/jsonnet-libs#612]
When using kube-proxy (as 99% of Kubernetes installations do, at the time of writing), a Service is implemented as a set of iptables rules mapping from each port on a virtual IP address to all pod addresses in the endpoint set.  Each time a pod is added or removed, the entire set of rules for that port is rewritten on every node, which can take an appreciable time once you get to hundreds of endpoints.

The Prometheus scrape config knows that ports ending `-metrics` are for scraping. We don't want to scrape metrics via a Service, since it would pick one endpoint at random hence receive inconsistent values. Therefore [`serviceFor`](https://github.com/grafana/jsonnet-libs/blob/2619bb87ecb336a59616df4c1fe8ced668bdbc94/ksonnet-util/util.libsonnet#L12) could leave those ports off the Service, saving the time that would have been spent updating those iptables rules.

**Comment by jdbaldry** [comment]
I think there is the case that a number of HTTP servers that have the metrics on the same port as the server and you may want the port to be an Endpoint and also the target for Prometheus. I do think being able to selectively expose App ports using `serviceFor` would be nice. Perhaps adding filter function to the signature that takes an array of container ports as input? Something like:
```jsonnet
serviceFor(deployment, ignored_labels=[], nameFormat='%(container)s-%(port)s', filter_fn=function(_) true):: ...
```

**Comment by bboreham** [comment]
Ah, I hadn't considered the case where a port is meant as both metrics and non-metrics.
Then I wondered if naming it twice was a good solution, and it turns out that is a five-year-old bug! https://github.com/kubernetes/kubernetes/issues/39188

**Comment by Duologic** [comment]
Lovely bug!

@jdbaldry How much I like that idea, I have a feeling it might get over-engineered quickly. How about a simple `ignore_ports=[]` list?
