### ISSUE TITLE
Consider tagging the repo

### ISSUE THREAD

**Issue by rhowe** [grafana/jsonnet-libs#639]
For those of us stuck behind hostile proxies such as Artifactory it would be really helpful if tags were published as the Artifactory VCS API doesn't support retrieving a repo via a commit ID (as far as I can tell). It only supports tags and branches and referencing the `master` branch I just know is going to lead to build instability.

Exactly what those tags would be I don't know - potentially just based on the dates? Daily or weekly snapshots?

**Comment by rsvas** [comment]
Having tags to maintain stable released would greatly help. Always pulling from master/main branches is causing lot's of issues in development. Can we please start tagging?!!!

**Comment by rhowe** [comment]
Note that I'm not necessarily asking for stable releases, just some tags - they don't need to come with any particular assurances aside from that they won't be changed.
