### ISSUE TITLE
Consolidate postgres-mixin

### ISSUE THREAD

**Issue by Duologic** [grafana/jsonnet-libs#726]
The postgres-mixin has a place in [upstream](https://github.com/prometheus-community/postgres_exporter/tree/master/postgres_mixin), should we consider removing it from grafana/jsonnet-libs before it diverges too much?

cc @kavirajk @jeschkies @tomwilkie

**Comment by tomwilkie** [comment]
Yes please!

**Comment by kavirajk** [comment]
Sure. Thanks @Duologic

**Comment by jeschkies** [comment]
Sure!
