### ISSUE TITLE
Docker mixin issues

### ISSUE THREAD

**Issue by RutgerKe** [grafana/jsonnet-libs#754]
Thanks for the integration! It looks really slick. I've however run into a few issues when using it:

- Inode usage should be grouped per instance (in addition to device), currently it is only grouped by 'device' and that gives weird results when 'device' names are not so unique. (see negative percentage in screenshot)
![Pasted image 20220329125835](https://user-images.githubusercontent.com/6214906/160611773-63d15d7f-3c64-4768-b7e6-83e7bc6c7ae0.png)
- The 'total containers' can give fractional numbers when they are starting/stopping. Either change the name to 'Mean number of containers' or change the panel calculation to 'last'. Same for 'total Images'. (I personally prefer 'last' I think)
- This dashboards is set to 'shared-tooltip', which creates overlapping popups quite quickly when not filtering to just a few containers. Probably best to set this to 'default'.
- Stacking makes it hard to see changes in individual timeseries, and in this dashboard seems to sometimes break compeletly. With stack:
![Pasted image 20220329131016](https://user-images.githubusercontent.com/6214906/160611776-fe58da10-e999-4ac6-88bd-42f9e714aad5.png)
- Without stacking
![Pasted image 20220329131046](https://user-images.githubusercontent.com/6214906/160611780-476157e7-ffec-4020-a90c-2d6aff7989bb.png)

The latter makes it harder to see a total number of connections, but the first gives a misleading idea of fluctuations.

**Comment by mshahzeb** [comment]
Fixes pushed in PR: https://github.com/grafana/jsonnet-libs/pull/759

@RutgerKe

**Comment by mshahzeb** [comment]
Marking this as resolved since the new integration version is now live.
