### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by rgeyer** [grafana/jsonnet-libs#808]
Anyone opposed to changing the default branch to `main`? Per https://github.com/github/renaming

**Comment by Duologic** [comment]
Branch renaming is a pain for jsonnet-bundler, it'll break `jb update` causing a lot of work for users of this repo.

**Comment by rgeyer** [comment]
> Branch renaming is a pain for jsonnet-bundler, it'll break `jb update` causing a lot of work for users of this repo.

Yes, this was discussed outside of this issue. This concern was raised, and it seems more than reason enough to leave things as is.

I'll close this.
