### ISSUE TITLE
Where did promeditor go?

### ISSUE THREAD

**Issue by seanmalloy** [grafana/jsonnet-libs#82]
I see that promeditor was removed from this repo. Did the code get moved to a different repo somewhere?

**Comment by tomwilkie** [comment]
Hi @seanmalloy!  @davkal is best to answer, AFAIK it got merged into grafana.

**Comment by davkal** [comment]
Moved to personal repo: https://github.com/davkal/promeditor

Let me know if it's still useful. Also, you can find an advanced version now in Grafana:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/components/PromQueryField.tsx
