### ISSUE TITLE
Traefik dashboard has hard coded services

### ISSUE THREAD

**Issue by regner** [grafana/jsonnet-libs#915]
The Traefik dashboard has a panel for "Requests by service" that instead of using `$service` is hard coded with `.*grafana@.*|prometheus.*|gitea.*` which is probably not relevant to most.

https://github.com/grafana/jsonnet-libs/blob/master/traefik-mixin/dashboards/traefikdash.json#L1452

**Comment by v-zhuravlev** [comment]
Thanks for spotting this.
